Backend - Simplified sample compilation There is not need to install Java, run swagger codegen, build and install the package. The pipelines can be compiled without all that.

diff --git a/backend/Dockerfile b/backend/Dockerfile
--- a/backend/Dockerfile
+++ b/backend/Dockerfile
@@ -14,24 +14,18 @@ COPY . .
 RUN apk add --update gcc musl-dev
 RUN go build -o /bin/apiserver backend/src/apiserver/*.go
 
-FROM python:3.5 as compiler
+FROM python:3.5 as sample-compiler
 
-RUN apt-get update -y && \
-    apt-get install --no-install-recommends -y -q default-jdk wget 
+COPY . /pipelines
 
-RUN pip3 install setuptools==40.5.0
-
-RUN wget http://central.maven.org/maven2/io/swagger/swagger-codegen-cli/2.3.1/swagger-codegen-cli-2.3.1.jar -O /tmp/swagger-codegen-cli.jar
-
-WORKDIR /go/src/github.com/kubeflow/pipelines
-COPY . .
-WORKDIR /go/src/github.com/kubeflow/pipelines/sdk/python
-RUN ./build.sh /kfp.tar.gz
-RUN pip3 install /kfp.tar.gz
-
-WORKDIR /samples
-COPY ./samples .
-RUN  find . -maxdepth 2 -name "*.py" -exec dsl-compile --py {} --output {}.tar.gz \;
+#We need to check that all samples have been compiled without error.
+#For find program, the -exec argument is a filter predicate just like -name. It only affects whether the file is "found", not the find's exit code.
+#One way to solve this problem is to check whether we have any python pipelines that cannot compile. Here the exit code is the number of such files:
+#RUN  bash -e -c 'exit $(find . -maxdepth 2 -name "*.py" ! -exec dsl-compile --py {} --output {}.tar.gz \; -print | wc -l)'
+#I think it's better to just use a shell loop though.
+#RUN  for pipeline in $(find . -maxdepth 2 -name '*.py' -type f); do dsl-compile --py "$pipeline" --output "$pipeline.tar.gz"; done
+#The "for" loop breaks on all whitespace, so we either need to override IFS or use the "read" command instead.
+RUN  find /pipelines/samples -maxdepth 2 -name '*.py' -type f | while read pipeline; do PYTHONPATH=/pipelines/sdk/python "$pipeline"; done
 
 FROM alpine
 
@@ -44,7 +38,7 @@ COPY --from=builder /bin/apiserver /bin/apiserver
 COPY --from=builder /go/src/github.com/kubeflow/pipelines/third_party/license.txt /bin/license.txt
 COPY backend/src/apiserver/config/ /config
 
-COPY --from=compiler /samples/ /samples/
+COPY --from=sample-compiler /pipelines/samples /samples
 
 # Adding CA certificate so API server can download pipeline through URL
 RUN apk add ca-certificates
