Merge remote-tracking branch 'upstream/master' into sync_refactor
Signed-off-by: Gabriel Rudloff <gabriel.rudloff@eviden.com>

diff --git a/test/release/Makefile b/test/release/Makefile
--- a/test/release/Makefile
+++ b/test/release/Makefile
@@ -12,18 +12,25 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-REMOTE=ghcr.io/kubeflow/kfp-release:1.1
+REMOTE=ghcr.io/kubeflow/kfp-release:master
 
 CONTAINER_ENGINE ?= docker
 
 .PHONY: release
 release:
-	# Usage: TAG=<TAG> BRANCH=<BRANCH> make release
+	# Usage: TAG=<TAG> BRANCH=<BRANCH> FORK_REMOTE=<FORK_REMOTE> make release
 	# Example, release in release branch:
-	#   TAG=1.4.0 BRANCH=release-1.4 make release
+	#   TAG=1.4.0 BRANCH=release-1.4 FORK_REMOTE=git@github.com:myuser/pipelines.git make release
 	# Example, release in master branch:
-	#   TAG=2.0.0-rc.1 BRANCH=master make release
-	./release.sh $(TAG) $(BRANCH)
+	#   TAG=2.0.0-rc.1 BRANCH=master FORK_REMOTE=git@github.com:myuser/pipelines.git make release
+	# FORK_REMOTE must NOT point to kubeflow/pipelines org
+	@if [ -z "$(FORK_REMOTE)" ]; then \
+		echo "ERROR: FORK_REMOTE is required"; \
+		echo "Usage: TAG=<TAG> BRANCH=<BRANCH> FORK_REMOTE=<FORK_REMOTE> make release"; \
+		echo "Example: TAG=1.4.0 BRANCH=release-1.4 FORK_REMOTE=git@github.com:myuser/pipelines.git make release"; \
+		exit 1; \
+	fi
+	./release.sh $(TAG) $(BRANCH) $(FORK_REMOTE)
 
 .PHONY: release-in-place
 release-in-place:
