Add force minio error test

diff --git a/components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests b/components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests
--- a/components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests
+++ b/components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests
@@ -126,6 +126,8 @@ function install_kfp() {
 
   kubectl wait --for=condition=ready -n "${KFP_NAMESPACE}" pod -l app=minio --timeout=5m
   kubectl port-forward -n kubeflow svc/minio-service $MINIO_LOCAL_PORT:9000 &
+  echo "Forcing error"
+  exit 1
   MINIO_PID=$!
 
   echo "[Installing KFP] Minio port-forwarded to ${MINIO_LOCAL_PORT}"
@@ -158,7 +160,7 @@ function delete_generated_role() {
 
 function cleanup_kfp() {
   # Clean up Minio
-  if [ ! -z "${MINIO_PID}" ]; then
+  if [[ ! -z "${MINIO_PID:-}" ]]; then
     kill -9 $MINIO_PID || true
   fi
 }
