Add working FSx setup and test

diff --git a/components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests b/components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests
--- a/components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests
+++ b/components/aws/sagemaker/tests/integration_tests/scripts/run_integration_tests
@@ -9,6 +9,7 @@ usage(){
 }
 
 cwd=$(dirname $(realpath $0))
+source "$cwd"/fsx_setup
 
 ### Input parameters
 DEPLOY_NAME="sagemaker-kfp-"$(date '+%Y-%m-%d-%H-%M-%S')"" # The name given to the entire deployment (tagging all resources)
@@ -29,6 +30,8 @@ KFP_SERVICE_ACCOUNT=${KFP_SERVICE_ACCOUNT:-"pipeline-runner"}
 PYTEST_MARKER=${PYTEST_MARKER:-""}
 S3_DATA_BUCKET=${S3_DATA_BUCKET:-""}
 SAGEMAKER_EXECUTION_ROLE_ARN=${SAGEMAKER_EXECUTION_ROLE_ARN:-""}
+
+SKIP_FSX_TESTS=${SKIP_FSX_TESTS:-"false"}
 
 while getopts ":n:r:s:" opt; do
   case $opt in
@@ -61,6 +64,12 @@ fi
 
 if [ "$S3_DATA_BUCKET" == "" ]; then
   echo "Missing S3 data bucket name"
+  usage
+  exit 1
+fi
+
+if [[ "$SKIP_FSX_TESTS" == "false" && "$EKS_PRIVATE_SUBNETS" == "" ]]; then
+  echo "Missing EKS private subnets"
   usage
   exit 1
 fi
@@ -143,6 +152,13 @@ function delete_generated_role() {
 }
 
 function cleanup_kfp() {
+  if [[ "${SKIP_FSX_TESTS}" == "false" ]]; then
+    delete_fsx_instance
+    # Sleep in order for the security group to detach before attempting to delete it
+    sleep 5s
+    cleanup_fsx_security_group
+  fi
+  
   # Clean up Minio
   if [ ! -z "${MINIO_PID}" ]; then
     kill -9 $MINIO_PID || true
@@ -150,11 +166,24 @@ function cleanup_kfp() {
 }
 
 if [[ -z "${EKS_EXISTING_CLUSTER}" ]]; then
-  launch_eks
+  # Launch all of these in parallel to reduce start-up time
+  launch_eks &
+
+  if [[ "${SKIP_FSX_TESTS}" == "false" ]]; then
+    create_fsx_security_group
+    create_fsx_instance &
+  fi
+
+  wait
 else
   aws eks update-kubeconfig --name "${EKS_EXISTING_CLUSTER}" --region "$REGION"
   EKS_CLUSTER_NAME="${EKS_EXISTING_CLUSTER}"
   DEPLOY_NAME="${EKS_EXISTING_CLUSTER}"
+
+  if [[ "${SKIP_FSX_TESTS}" == "false" ]]; then
+    create_fsx_security_group
+    create_fsx_instance
+  fi
 fi
 
 generate_iam_role_name
@@ -163,6 +192,16 @@ install_kfp
 install_generated_role
 
 pytest_args=( --region "${REGION}" --role-arn "${SAGEMAKER_EXECUTION_ROLE_ARN}" --s3-data-bucket "${S3_DATA_BUCKET}" --minio-service-port "${MINIO_LOCAL_PORT}" --kfp-namespace "${KFP_NAMESPACE}" )
+
+if [[ "${SKIP_FSX_TESTS}" == "false" ]]; then
+  # Get the VPC arguments for the FSx test
+  IFS=',' read -r -a private_subnets <<< "$EKS_PRIVATE_SUBNETS"
+  pytest_args+=( --fsx-subnet "${private_subnets[0]}" --fsx-security-group "${FSX_SECURITY_GROUP_ID}" --fsx-id "${FSX_ID}" )
+fi
+
 [ ! -z "${PYTEST_MARKER}" ] && pytest_args+=( -m "${PYTEST_MARKER}" )
+
+# TODO: DELETE BEFORE MERGING PR
+pytest_args+=( -k 'test_fsx_trainingjob' )
 
 cd tests/integration_tests && python -m pytest "${pytest_args[@]}" --junitxml ./integration_tests.log -n $(nproc)
