merge
Signed-off-by: arpechenin <arpechenin@avito.ru>

diff --git a/.github/workflows/legacy-v2-api-integration-tests.yml b/.github/workflows/legacy-v2-api-integration-tests.yml
--- a/.github/workflows/legacy-v2-api-integration-tests.yml
+++ b/.github/workflows/legacy-v2-api-integration-tests.yml
@@ -97,9 +97,16 @@ jobs:
           PIPELINE_STORE: ${{ matrix.pipeline_store }}
         continue-on-error: true
 
+      - name: Debug TLS cert secret
+        if: ${{ always() && matrix.pod_to_pod_tls_enabled }}
+        run: |
+          echo "=== Trying to get kfp-api-tls-cert secret ==="
+          kubectl get secret kfp-api-tls-cert -n kubeflow || echo "Secret not found"
+
       - name: Collect failed logs
         if: ${{ steps.deploy.outcome != 'success' || steps.forward-mlmd-port.outcome != 'success' || steps.tests.outcome != 'success' }}
         run: |
+          kubectl get secret kfp-api-tls-cert -n kubeflow
           ./.github/resources/scripts/collect-logs.sh --ns kubeflow --output /tmp/tmp_pod_log.txt
           exit 1
 
